// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWTrEZnyW8dY7EK5fcaky-RFLFPeonpnQ',
    appId: '1:843401690554:web:62fe24bf6c91654bc4f183',
    messagingSenderId: '843401690554',
    projectId: 'spark-asha',
    authDomain: 'spark-asha.firebaseapp.com',
    storageBucket: 'spark-asha.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc-_3lBKiVxKu03YLv-s7gZdW7ux7xqUQ',
    appId: '1:843401690554:android:8cefe74a8665af8bc4f183',
    messagingSenderId: '843401690554',
    projectId: 'spark-asha',
    storageBucket: 'spark-asha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqgY4zQjxQagaRJk9xCF_mr1ssW5yXxwQ',
    appId: '1:843401690554:ios:38bd3e0b701b62c4c4f183',
    messagingSenderId: '843401690554',
    projectId: 'spark-asha',
    storageBucket: 'spark-asha.firebasestorage.app',
    iosBundleId: 'com.sparkapp.spark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqgY4zQjxQagaRJk9xCF_mr1ssW5yXxwQ',
    appId: '1:843401690554:ios:38bd3e0b701b62c4c4f183',
    messagingSenderId: '843401690554',
    projectId: 'spark-asha',
    storageBucket: 'spark-asha.firebasestorage.app',
    iosBundleId: 'com.sparkapp.spark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWTrEZnyW8dY7EK5fcaky-RFLFPeonpnQ',
    appId: '1:843401690554:web:f03aff6e13c37a08c4f183',
    messagingSenderId: '843401690554',
    projectId: 'spark-asha',
    authDomain: 'spark-asha.firebaseapp.com',
    storageBucket: 'spark-asha.firebasestorage.app',
  );

}